vitamedline/MedLine/Controllers/PagamentoController.cs
using MedLine.Models.Comum;
using MedLine.Models.Enums;
using MedLine.Models.Financa;
using MedLine.Models.Identity;
using MedLine.Services.ComumServices;
using MedLine.Services.FinancaServices;
using MedLine.Services.LaboratorioServices;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MedLine.Controllers
{
    public class PagamentoController : BaseController
    {
        private AppDbContext db = new AppDbContext();
        private PagamentosServices labServices = new PagamentosServices();

        // GET: Pagamento
        public ActionResult Index()
        {
            var list = labServices.MapPacientesGroup();
            return View(list);
        }

        public ActionResult PagamentosPendentes(int pacienteId)
        {
            var list = labServices.MapPagamentos(pacienteId);
            var paciente = db.Pacientes.Find(pacienteId);
            ViewBag.Paciente = paciente;
            return View(list);
        }

        public ActionResult EfectuarPagamento(int id, int pacienteId)
        {
            var model = db.Pagamentos.Find(id);

            ViewBag.TipoPagamento = new SelectList(Enum.GetValues(typeof(ETipoPagamento)).Cast<ETipoPagamento>().ToList().Select(x => new { Id = x, Value = Extensions.GetDescription(x) }), "Id", "Value");
            var paciente = db.Pacientes.Find(pacienteId);
            ViewBag.Paciente = paciente;
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EfectuarPagamento(Pagamento pagamento, int id, int pacienteId)
        {
            var model = db.Pagamentos.Find(id);
            if (pagamento.FormaPagamento == EFormaPagamento.SeguroSaude)
            {
                if (SessionFile.Count() < 1)
                {
                    ModelState.AddModelError("", "Nenhum anexo de comprovativo para o seguro de saúde");
                }
            }
            else
            {
                if ( model.PagamentosDetalhes.Sum(x=>x.Valor)>pagamento.ValorPago)
                {
                    ModelState.AddModelError("", "Nenhum Valor entregue menor");
                }
            }
            if (ModelState.IsValid)
            {
                model.ValorPago = pagamento.ValorPago;
                model.Pago = true;
                model.FormaPagamento = pagamento.FormaPagamento;
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();

                var agendamento = db.Agendamentos.Find(model.AgendamentoId);
                if (agendamento.Estado != EEstadoAgendamento.Finalizada || 
                    agendamento.Estado != EEstadoAgendamento.Consulta || 
                    agendamento.Estado != EEstadoAgendamento.Laboratório)
                {
                    agendamento.Estado = EEstadoAgendamento.Triagem;
                    db.Entry(agendamento).State = EntityState.Modified;
                    db.SaveChanges();
                }
                var analise = agendamento.Analises.FirstOrDefault();
                if (analise != null)
                {
                    foreach (var item in analise.AnalisesExamesLaboratorio)
                    {
                        var lab = db.AnalisesExames.Find(item.Id);
                        lab.EstadoAnaliseExame = EEstadoAnaliseExame.Laboratorio;
                        db.Entry(lab).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                }
                SaveFicheiros(model.Id);
                return RedirectToAction("PagamentosPendentes", new { pacienteId = pacienteId });
            }

            ViewBag.TipoPagamento = new SelectList(Enum.GetValues(typeof(ETipoPagamento)).Cast<ETipoPagamento>().ToList().Select(x => new { Id = x, Value = Extensions.GetDescription(x) }), "Id", "Value");
            var paciente = db.Pacientes.Find(pacienteId);
            ViewBag.Paciente = paciente;
            return View(pagamento);
        }

        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase file)
        {
            string fileName = "";
            if ((file == null ? false : file.ContentLength > 0))
            {
                fileName = Path.GetTempPath() + Guid.NewGuid().ToString() + Path.GetFileName(file.FileName);
                file.SaveAs(fileName);
                Ficheiro ficheiro = new Ficheiro
                {
                    Descricao = file.FileName,
                    File = System.IO.File.ReadAllBytes(fileName),
                    TipoFicheiro = ETipoFicheiro.Pagamento
                };
                SessionFile.Add(ficheiro);
                return Content(string.Empty);
            }
            return Content("Erro");
        }
        public ActionResult RemoveFile(string filename)
        {
            SessionFile.ForEach(o =>
            {
                if (o.Descricao == filename)
                {
                    SessionFile.Remove(o);
                }
            });
            return base.Content(string.Empty);
        }

    }
}

vitamedline/MedLine/Views/Pagamento/EfectuarPagamento.cshtml
@model MedLine.Models.Financa.Pagamento

@{
    ViewBag.Title = "Efectuar Pagamento";
    var paciente = (MedLine.Models.Pacientes.Paciente)ViewBag.Paciente;
    var ageServices = new MedLine.Services.ComumServices.AgeServices();
}

<div class="container">
    <div class="row">
        <div class="menu-lateral pull-left margin-top col-md-2">
            <h3 class="title">Notificações</h3>
            <h6 class="titulo-alerta text-muted">Lista:</h6>
            <ul class="notice list-unstyled">
                <li>
                    <a href="">
                        Notificação<i class="fa fa-calendar"></i>
                    </a>
                </li>
            </ul>
        </div>
        <div class="col-md-10 col-xs-12 pull-right">
            <!-- Tab panes -->
            <div class="content clear">
                <div class="row">
                    <h2 class="page-header">Paciente: <span>@paciente.Nome</span></h2>
                    <h4 class="text-muted title">
                        #@paciente.Codigo<br />
                        <small>@ageServices.GetAgeDescription(paciente.DataNascimento)</small>
                        <small>- @paciente.Agendamentos.Count()ª Consulta</small>
                        <br />
                        <small><strong class="exame">Agendamento: </strong>@Model.Agendamento.Codigo | @Model.Agendamento.DataRegisto.ToString("dd-MM-yyyy HH:mm")</small>
                        <br />
                        <small><strong class="exame">Pagamento: </strong>@Model.Codigo</small>
                        <br />
                        <small><strong class="exame">Data Registo:</strong> @Model.DataRegisto.ToString("dd-MM-yyyy HH:mm") </small>
                        <br />
                        <small><strong class="exame">TOTAL: </strong> @Model.Total.ToString("C3")</small>
                    </h4>
                    <h4 class="section-title">Lista de Serviços</h4>
                    <div class="table-responsive">
                        <div class="fresh-table-container">
                            <table id="fresh-table" class="table tabela-with-advancedSearch" data-toolbar="#toolbar">
                                <thead>
                                    <tr>
                                        <th>
                                            @("CID")
                                        </th>
                                        <th>
                                            @("Serviço")
                                        </th>
                                        <th>
                                            @("Valor")
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.PagamentosDetalhes)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.AreaActuacao.CID)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.AreaActuacao.Nome)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.AreaActuacao.Valor)
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td>
                                            TOTAL:
                                        </td>
                                        <td rowspan="2">
                                            <span id="myTotal">
                                                @Model.PagamentosDetalhes.Sum(x => x.AreaActuacao.Valor)
                                            </span>
                                        </td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>

                    <h4 class="section-title">Anexar Ficheiros</h4>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="panel panel-blue">
                                <div class="panel-heading">Adicionar Ficheiros</div>
                                <div class="panel-body">
                                    <form action="@Url.Action("UploadFile")" method="post" enctype="multipart/form-data" class="dropzone" id="dropzoneForm">
                                        <div class="fallback">
                                            @Html.Hidden("TipoFicheiro", MedLine.Models.Enums.ETipoFicheiro.Pagamento)
                                            <input name="file" type="file" multiple />
                                            <input type="submit" value="Carregar" />
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <h4 class="section-title">Submeter Dados</h4>
                    @using (Html.BeginForm("EfectuarPagamento", "Pagamento", FormMethod.Post, new { @class = "form-novo-paciente margin-top form-horizontal" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.Id)
                        @Html.HiddenFor(model => model.Total)
                        @Html.HiddenFor(model => model.SubTotal)
                        @Html.HiddenFor(model => model.Sequencia)
                        @Html.HiddenFor(model => model.DataRegisto)
                        @Html.HiddenFor(model => model.Codigo)
                        @Html.HiddenFor(model => model.AgendamentoId)
                        @Html.Hidden("pacienteId", paciente.Id)

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group col-sm-6 form-group-sm">
                            @Html.LabelFor(model => model.FormaPagamento, htmlAttributes: new { @class = "control-label " })
                            @Html.EnumDropDownListFor(model => model.FormaPagamento, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.FormaPagamento, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-sm-3 form-group-sm">
                            @Html.LabelFor(model => model.ValorPago, htmlAttributes: new { @class = "control-label " })
                            @Html.EditorFor(model => model.ValorPago, new { @class = "form-control autoNumber" })
                            @Html.ValidationMessageFor(model => model.ValorPago, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-sm-3 form-group-sm">
                            @Html.Label("Troco", htmlAttributes: new { @class = "control-label " })
                            @Html.Editor("Troco", new { @class = "form-control", @readonly = "readonly" })
                            @Html.ValidationMessage("Troco", "", new { @class = "text-danger" })
                        </div>
                        <hr />
                            <div class="row">
                                <div class="col-sm-6 pull-right">
                                    <div class="pull-right">
                                        <a href="@Url.Action("PagamentosPendentes", new { pacienteId = paciente.Id })" class="btn btn-warning btn-sm btn-fill">
                                            <i class="fa fa-arrow-left"></i>
                                        </a>
                                        <button type="submit" class="btn btn-sm btn-fill btn-warning">
                                            Guardar
                                        </button>
                                    </div>
                                </div>
                            </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>

vitamedline/MedLine/Views/Pagamento/Index.cshtml
@model IEnumerable<MedLine.Models.Comum.ViewModel.PacientesViewModel>
@{
    ViewBag.Title = "Caixa";
    var notifications = (List<string>)ViewBag.Notifications;
}

<h2> Pendentes Laboratório</h2>
<div class="col-md-2">
    <div class="menu-lateral pull-left margin-top col-md-6">
        <h3 class="title">Notificações</h3>
        <h6 class="titulo-alerta text-muted">Lista:</h6>
        <ul class="notice list-unstyled">
            <li>
                <a href="">
                    Notificação 1 <i class="fa fa-calendar"></i>
                </a>
                <a href="">
                    Notificação 2 <i class="fa fa-calendar"></i>
                </a>
            </li>
        </ul>
    </div>
</div>

<div class="col-md-10 col-xs-12 pull-right">
    <div class="content">

        <!-- Tab panes -->
        <div class="content">
            <div class="tab-content">
                <div class="tab-pane active" id="list">
                    <div class="row">
                        <h2 class="page-header">Pagamentos Pendentes</h2>
                        <div class="table-responsive">
                            <div class="fresh-table-container">
                                <table id="fresh-table" class="table tabela-with-advancedSearch" data-toolbar="#toolbar">
                                    <thead>
                                        <tr>
                                            <th>
                                                @("# Paciente")
                                            </th>
                                            <th>
                                                @("Nome")
                                            </th>
                                            <th>
                                                @("Tipo Cliente")
                                            </th>
                                            <th>
                                                @("Idade")
                                            </th>
                                            <th>
                                                @("Sexo")
                                            </th>
                                            <th>
                                                @("Telefone")
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @(item.CodigoPaciente)
                                                </td>
                                                <td>
                                                    @(item.NomePaciente)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.TipoCliente)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Idade)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Sexo)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Telefone)
                                                </td>
                                                <td>
                                                    <a data-tooltip="tooltip" title="Ver pagamentos pendentes" class="table-action btn btn-simple btn-info" href="@Url.Action("PagamentosPendentes", new { pacienteId = item.Id })">
                                                        <i class="fa fa-bars"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

vitamedline/MedLine/Views/Pagamento/PagamentosPendentes.cshtml
@model IEnumerable<MedLine.Models.Financa.Pagamento>

@{
    ViewBag.Title = "Pagamentos pendentes";
    var notifications = (List<string>)ViewBag.Notifications;
    var paciente = (MedLine.Models.Pacientes.Paciente)ViewBag.Paciente;
    var ageServices = new MedLine.Services.ComumServices.AgeServices();
}

<div class="col-md-2">
    <div class="menu-lateral pull-left margin-top col-md-6">
        <h3 class="title">Notificações</h3>
        <h6 class="titulo-alerta text-muted">Lista:</h6>
        <ul class="notice list-unstyled">
            <li>
                <a href="">
                    Notificação 3 <i class="fa fa-calendar"></i>
                </a>
            </li>
        </ul>
    </div>
</div>

<div class="col-md-10 col-xs-12 pull-right">
    <div class="content">

        <!-- Tab panes -->
        <div class="content">
            <div class="tab-content">
                <div class="tab-pane active" id="list">

                    <div class="row">
                        <h2 class="page-header">Agendamento: <span>#@paciente.Codigo</span></h2>
                        <h4 class="text-muted title">
                            @paciente.Nome<br />
                            <small>@ageServices.GetAgeDescription(paciente.DataNascimento)</small>
                        </h4>
                    </div>
                    <div class="row">
                        <h2 class="page-header">Pagamentos Pendentes</h2>
                        <div class="table-responsive">
                            <div class="fresh-table-container">
                                <table id="fresh-table" class="table tabela-with-advancedSearch" data-toolbar="#toolbar">
                                    <thead>
                                        <tr>
                                            <th>
                                                @("Cód. Agendamento")
                                            </th>
                                            <th>
                                                @("Serviço")
                                            </th>
                                            <th>
                                                @("Data Registo")
                                            </th>
                                            <th>
                                                @("Cod. Pagamento")
                                            </th>
                                            <th>
                                                @("Total")
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Agendamento.Codigo)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Agendamento.AreaActuacao.CID) -
                                                    @Html.DisplayFor(modelItem => item.Agendamento.AreaActuacao.Nome)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.DataRegisto)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Codigo)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Total)
                                                </td>
                                                <td>
                                                    <a data-tooltip="tooltip" title="Efectuar pagamento" class="table-action btn btn-simple btn-info" href="@Url.Action("EfectuarPagamento", new { id = item.Id, pacienteId = paciente.Id })">
                                                        <i class="fa fa-money"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>