vitamedline/MedLine/Controllers/ConsultaController.cs
using MedLine.Models.Identity;
using MedLine.Services.AgendamentoServices;
using MedLine.Services.ComumServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using MedLine.Models.Consulta;
using MedLine.Models.Enums;
using MedLine.Services.FinancaServices;
using MedLine.Models.Laboratorio;
using MedLine.Models.Financa;

namespace MedLine.Controllers
{
    public class ConsultaController : Controller
    {
        private AppDbContext db = new AppDbContext();
        private VitaServices vitaServices = new VitaServices();
        private AgendamentoServices agendamentoservice = new AgendamentoServices();
        private PagamentosServices pagamentosServices = new PagamentosServices();

        public ActionResult Index()
        {

            var agendamentos = db.Agendamentos.Include(t => t.Paciente).Include(t => t.Funcionario).Include(t => t.AreaActuacao).OrderBy(t => t.DataConsulta).ToList();
            return View(agendamentos);
        }

        public ActionResult Triagem()
        {
            var list = db.Agendamentos.Where(s => s.Estado == Models.Enums.EEstadoAgendamento.Triagem
                            //&&DbFunctions.TruncateTime(s.Agendamento.DataConsulta) == DbFunctions.TruncateTime(DateTime.Now)
                            );
            return View(list);
        }

        public ActionResult NovaTriagem(int id)
        {
            var agendamento = db.Agendamentos.Find(id);
            ViewBag.Agendamento = agendamento;
            return View();
        }
        [HttpPost]
        public ActionResult NovaTriagem(Triagem model)
        {
            if (ModelState.IsValid)
            {
                db.Triagens.Add(model);
                db.SaveChanges();
                agendamentoservice.ChangeStatus(model.AgendamentoId, EEstadoAgendamento.Consulta);
                return RedirectToAction("Triagem");
            }

            var agendamento = db.Agendamentos.Find(model.AgendamentoId);
            ViewBag.Agendamento = agendamento;
            return View(model);
        }

        [HttpPost]
        public ActionResult FinalizarConsulta(int agendamentoId)
        {
            var agendamento = db.Agendamentos.Find(agendamentoId);
            if(agendamento.Estado == EEstadoAgendamento.Laboratório)
            {
                agendamento.Estado = EEstadoAgendamento.Finalizada;
                db.Entry(agendamento).State = EntityState.Modified;
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult GuardarAnalise(Analise analise)
        {
            var agendamento = db.Agendamentos.Find(analise.AgendamentoId);

            if (!db.Analises.Any(t => t.AgendamentoId == agendamento.Id))
            {
                analise.DataInicio = DateTime.Now;


                if (ModelState.IsValid)
                {
                    db.Analises.Add(analise);
                    db.SaveChanges();
                }
            } else
            {
                var model = db.Analises.First(t => t.AgendamentoId == agendamento.Id);
                TryUpdateModel(model);
                db.SaveChanges();
            }

            return RedirectToAction("NovoAtendimento", new { id = analise.AgendamentoId });
        }

        [HttpPost]
        public ActionResult GuardarDiagnostico(AnaliseDiagnostico diag)
        {
            var analise = db.Analises.Find(diag.AnaliseId);
            
            if (!db.AnalisesDiagnosticos.Any(t => t.AnaliseId == analise.Id))
            {
                if (ModelState.IsValid)
                {
                    db.AnalisesDiagnosticos.Add(diag);
                    db.SaveChanges();
                }
            }
            else
            {
                var model = db.AnalisesDiagnosticos.First(t => t.AnaliseId == analise.Id);
                TryUpdateModel(model);
                db.SaveChanges();
            }

            return RedirectToAction("NovoAtendimento", new { id = analise.AgendamentoId });
        }


        public ActionResult NovoAtendimento(int id)
        {
            var agendamento = db.Agendamentos.Include(t => t.Paciente).Include(t => t.Funcionario).Include(t => t.AreaActuacao).FirstOrDefault(t => t.Id == id);

            agendamento.Estado = EEstadoAgendamento.Consulta;
            db.Entry(agendamento).State = EntityState.Modified;
            db.SaveChanges();

            ViewBag.AreaActuacaoId = new SelectList(db.AreasActuacoes.Where(t => t.TipoAgendamentoId == (int)ETipoAgendamento.Laboratorio), "Id", "Nome");

            return View(agendamento);
        }

        [HttpPost]
        public ActionResult AdicionarExame(int AreaActuacaoId, int analiseId)
        {
            var analise = db.Analises.Find(analiseId);
            var agendamento = db.Agendamentos.Find(analise.AgendamentoId);
            var serviceoExame = db.AreasActuacoes.Find(AreaActuacaoId);

            int sequencia = 0;
            var codigo = pagamentosServices.GenerateCodigo(out sequencia);



            AnaliseExameLaboratorio analiseexame = new AnaliseExameLaboratorio
            {
                AreaActuacaoId = serviceoExame.Id,
                DataRegisto = DateTime.Now,
                EstadoAnaliseExame = EEstadoAnaliseExame.Pendente,
                AnaliseId = analiseId,
                PacienteId = agendamento.PacienteId
            };

            db.AnalisesExames.Add(analiseexame);
            db.SaveChanges();

            Pagamento pagamento = new Pagamento
            {
                AgendamentoId = agendamento.Id,
                DataRegisto = DateTime.Now,
                Pago = false,
                SubTotal = serviceoExame.Valor,
                Total = serviceoExame.Valor,
                Sequencia = sequencia,
                Codigo = codigo
            };
            db.Pagamentos.Add(pagamento);
            db.SaveChanges();

            PagamentoDetalhes pgDetalhe = new PagamentoDetalhes();
            pgDetalhe.AreaActuacaoId = serviceoExame.Id;
            pgDetalhe.PagamentoId = pagamento.Id;
            pgDetalhe.Valor = serviceoExame.Valor;
            db.PagamentosDetalhes.Add(pgDetalhe);
            db.SaveChanges();

            agendamento.Estado = Models.Enums.EEstadoAgendamento.Laboratório;
            db.Entry(agendamento).State = EntityState.Modified;
            db.SaveChanges();

            ViewBag.AreaActuacaoId = new SelectList(db.AreasActuacoes.Where(t => t.TipoAgendamentoId == (int)ETipoAgendamento.Laboratorio), "Id", "Nome");
            return RedirectToAction("NovoAtendimento", new { id =  analise.Agendamento.Id });
        }

    }
}

vitamedline/MedLine/Views/Consulta/Index.cshtml
@model IEnumerable<MedLine.Models.Consulta.Agendamento>
<div class="col-md-2">

	<div class="col-md-12"> <!-- required for floating -->
		<!-- Nav tabs -->
		<ul class="nav nav-tabs tabs-left">
			<li class="active"><a href="#list" data-toggle="tab">Listagem</a></li>
		</ul>
	</div>

	<div class="menu-lateral pull-left margin-top col-md-6">
		<h3 class="title">Notificações</h3>
		<h6 class="titulo-alerta text-muted">Lista:</h6>
		<ul class="notice list-unstyled">
				<li>
					<a href="">
						Paciente XPTO | Urgente <i class="fa fa-calendar"></i>
					</a>
				</li>
		</ul>
	</div>
</div>

<div class="col-md-10 col-xs-12 pull-right">
<div class="content">

<!-- Tab panes -->
<div class="content">
    <div class="tab-content">
        <div class="tab-pane active" id="list">

<div class="row">
<h2 class="page-header">Consultas</h2>
    <div class="table-responsive">
        <div class="fresh-table-container">
            <table class="table tabela-sem-opcoes">
                <thead>
                    <tr>
                        <th data-field="id">Paciente</th>
                        <th data-field="id">Cód.</th>
                        <th data-field="profissional de saude">Consultado por</th>
                        <th data-field="tipo agendamento">Tipo agendamento</th>
                        <th data-field="area">Área</th>
                        <th data-field="data">Data Hora</th>
                        <th data-field="hora">Hora</th>
                        <th data-field="estado">Estado</th>
                        <th>Opções</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.OrderBy(x => x.DataConsulta))//.Where(x => x.Estado == MedLine.Models.Enums.EEstadoAgendamento.Consulta))
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Paciente.Nome)</td>
                            <td>@Html.DisplayFor(modelItem => item.Codigo)</td>
                            <td>@Html.DisplayFor(modelItem => item.Funcionario.Nome)</td>
                            <td>@Html.DisplayFor(modelItem => item.AreaActuacao.TipoAgendamento.Nome)</td>
                            <td>@Html.DisplayFor(modelItem => item.AreaActuacao.Nome)</td>
                            <td>@(item.DataConsulta.ToString("dd-MM-yyyy"))</td>
                            <td>@(item.DataConsulta.ToString("HH:mm"))</td>
                            <td>@Html.DisplayFor(modelItem => item.Estado)</td>
                            <td>
                                <a class="table-action btn btn-simple btn-info" data-toggle="popover" data-placement="top" title="" data-content="@item.Observacoes" data-original-title="Observações"><i class="fa fa-info-circle"></i></a>
                                <a data-tooltip="tooltip" title="" class="table-action btn btn-simple btn-danger" href="@Url.Action("NovoAtendimento", "Consulta", new { id = item.Id })" data-original-title="Novo atendimento"><i class="fa fa-stethoscope"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</div>
</div>
</div>
</div>
</div>
</div>





vitamedline/MedLine/Views/Consulta/NovaTriagem.cshtml
@model Triagem

@using MedLine.Models.Consulta

@{
    ViewBag.Title = "Triagem";
    var agendamento = (Agendamento)ViewBag.Agendamento;
}

<div class="menu-lateral pull-left margin-top col-md-2">
    <h3 class="title">Notificações</h3>
    <h6 class="titulo-alerta text-muted">Lista:</h6>

    <ul class="notice list-unstyled">
        <li>
            <a href="">
                Notificação 1 <i class="fa fa-calendar"></i>
                Notificação 2 <i class="fa fa-calendar"></i>
                Notificação 3 <i class="fa fa-calendar"></i>
            </a>
        </li>
    </ul>
</div>
<div class="col-md-10 col-xs-12 pull-right">
    <div class="content clear">
        <div class="row">
            <h2 class="page-header">Triagem: @agendamento.Codigo | @agendamento.Paciente.Nome #@agendamento.Paciente.Codigo</h2>
            @using (Html.BeginForm("NovaTriagem", "Consulta", FormMethod.Post, new { @class = "form-novo-paciente" }))
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("AgendamentoId", agendamento.Id)
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group col-sm-3 form-group-sm">
                    @Html.LabelFor(model => model.Altura, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.Altura, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Altura, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-sm-3 form-group-sm">
                    @Html.LabelFor(model => model.Peso, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-sm-3 form-group-sm">
                    @Html.LabelFor(model => model.FrequenciaCardiaca, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.FrequenciaCardiaca, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FrequenciaCardiaca, "", new { @class = "text-danger" })
                </div>
                    <div class="form-group col-sm-3 form-group-sm">
                        @Html.LabelFor(model => model.Temperatura, htmlAttributes: new { @class = "control-label " })
                        @Html.EditorFor(model => model.Temperatura, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Temperatura, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-sm-3 form-group-sm">
                        @Html.LabelFor(model => model.Pulso, htmlAttributes: new { @class = "control-label " })
                        @Html.EditorFor(model => model.Pulso, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Pulso, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-sm-3 form-group-sm">
                        @Html.LabelFor(model => model.Respiracao, htmlAttributes: new { @class = "control-label " })
                        @Html.EditorFor(model => model.Respiracao, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Respiracao, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-sm-3 form-group-sm">
                        @Html.LabelFor(model => model.TensaoArterial, htmlAttributes: new { @class = "control-label " })
                        @Html.EditorFor(model => model.TensaoArterial, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TensaoArterial, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-sm-3 form-group-sm">
                        @Html.LabelFor(model => model.SinaisSintomas, htmlAttributes: new { @class = "control-label " })
                        @Html.EditorFor(model => model.SinaisSintomas, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SinaisSintomas, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-sm-12 form-group-sm">
                        @Html.LabelFor(model => model.Observacoes, htmlAttributes: new { @class = "control-label " })
                        @Html.TextAreaFor(model => model.Observacoes, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Observacoes, "", new { @class = "text-danger" })
                    </div>
                    <hr />
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="pull-right">
                                <a href="@Url.Action("Triagem")" class="btn btn-warning btn-sm btn-fill">
                                    <i class="fa fa-arrow-left"></i>
                                </a>
                                <button type="submit" class="btn btn-sm btn-fill btn-warning">
                                    Salvar
                                </button>
                            </div>
                        </div>
                    </div>
                    <br />
            }
        </div>
    </div>
</div>

vitamedline/MedLine/Views/Consulta/Triagem.cshtml
@model IEnumerable<MedLine.Models.Consulta.Agendamento>

@{
    ViewBag.Title = "Triagem";
    var notifications = (List<string>)ViewBag.Notifications;
}

<h2> Listagem de Triagem</h2>

<div class="col-md-2">

    <div class="col-md-12">
        <!-- required for floating -->
        <!-- Nav tabs -->
        <ul class="nav nav-tabs tabs-left">
            <li class="active"><a href="#list" data-toggle="tab">Listagem</a></li>
        </ul>
    </div>

    <div class="menu-lateral pull-left margin-top col-md-6">
        <h3 class="title">Notificações</h3>
        <h6 class="titulo-alerta text-muted">Lista:</h6>
        <ul class="notice list-unstyled">
            <li>
                <a href="">
                    Notificação 1 <i class="fa fa-calendar"></i>
                </a>
                <a href="">
                    Notificação 2 <i class="fa fa-calendar"></i>
                </a>
                <a href="">
                    Notificação 3 <i class="fa fa-calendar"></i>
                </a>
            </li>
        </ul>
    </div>
</div>

<div class="col-md-10 col-xs-12 pull-right">
    <div class="content">

        <!-- Tab panes -->
        <div class="content">
            <div class="tab-content">
                <div class="tab-pane active" id="list">

                    <div class="row">
                        <h2 class="page-header">Triagem</h2>
                        <div class="table-responsive">
                            <div class="fresh-table-container">
                                <table id="fresh-table" class="table tabela-with-advancedSearch" data-toolbar="#toolbar">
                                    <thead>
                                        <tr>
                                            <th>
                                                @("# Paciente")
                                            </th>
                                            <th>
                                                @("Nome")
                                            </th>
                                            <th>
                                                @("Profissional Saúde")
                                            </th>
                                            <th>
                                                @("Serviço")
                                            </th>
                                            <th>
                                                @("Hora da Consulta")
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @(item.Paciente.Codigo)
                                                </td>
                                                <td>
                                                    @(item.Paciente.Nome)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Funcionario.Nome)
                                                </td>
                                                <td>
                                                    @(item.AreaActuacao.CID + " - " + item.AreaActuacao.Nome + " | " + item.AreaActuacao.TipoAgendamento.Nome )
                                                </td>
                                                <td>
                                                    @(item.DataConsulta.ToString("HH:mm:ss"))
                                                </td>
                                                <td>
                                                    <a data-tooltip="tooltip" title="Fazer triagem" class="table-action btn btn-simple btn-info" href="@Url.Action("NovaTriagem", new { id = item.Id })">
                                                        <i class="fa fa-bars"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>