vitamedline/MedLine/Controllers/FicheiroesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MedLine.Models.Comum;
using MedLine.Models.Identity;

namespace MedLine.Controllers
{
    public class FicheiroesController : BaseController
    {
        private AppDbContext db = new AppDbContext();

        // GET: Ficheiroes
        public ActionResult Index()
        {
            return View(db.Ficheiros.ToList());
        }

        // GET: Ficheiroes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ficheiro ficheiro = db.Ficheiros.Find(id);
            if (ficheiro == null)
            {
                return HttpNotFound();
            }
            return View(ficheiro);
        }

        // GET: Ficheiroes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ficheiroes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Descricao,File,TipoFicheiro")] Ficheiro ficheiro)
        {
            if (ModelState.IsValid)
            {
                db.Ficheiros.Add(ficheiro);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ficheiro);
        }

        // GET: Ficheiroes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ficheiro ficheiro = db.Ficheiros.Find(id);
            if (ficheiro == null)
            {
                return HttpNotFound();
            }
            return View(ficheiro);
        }

        // POST: Ficheiroes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Descricao,File,TipoFicheiro")] Ficheiro ficheiro)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ficheiro).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ficheiro);
        }

        // GET: Ficheiroes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ficheiro ficheiro = db.Ficheiros.Find(id);
            if (ficheiro == null)
            {
                return HttpNotFound();
            }
            return View(ficheiro);
        }

        // POST: Ficheiroes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ficheiro ficheiro = db.Ficheiros.Find(id);
            db.Ficheiros.Remove(ficheiro);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

vitamedline/MedLine/Controllers/RelatórioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MedLine.Controllers
{
    public class RelatórioController : Controller
    {
        // GET: Relatório
        public ActionResult Index()
        {
            return View();
        }
    }
}

vitamedline/MedLine/Views/Shared/_DefinicoesMenu.cshtml
<ul class="nav nav-tabs tabs-left">
    <li class="@( ViewContext.RouteData.Values["controller"].ToString().ToLower() == "Ficheiros".ToLower() ?"active": "" )"><a href="@Url.Action("Index","Ficheiroes")">Servidor Ficheiros</a></li>
    <li class="@( ViewContext.RouteData.Values["controller"].ToString().ToLower() == "Definicoeos".ToLower() ?"active": "" )"><a href="@Url.Action("Index","Definicoeos")">Entidade</a></li>
    <li class="@( ViewContext.RouteData.Values["controller"].ToString().ToLower() == "Account".ToLower() ?"active": "" )"><a href="@Url.Action("Index","Account")">Utilizadores</a></li>
    <li class="@( ViewContext.RouteData.Values["controller"].ToString().ToLower() == "Sexoes".ToLower() ?"active": "" )"><a href="@Url.Action("Index","Sexoes")">Sexo</a></li>
    <li class="@( ViewContext.RouteData.Values["controller"].ToString().ToLower() == "TipoAgendamentoes".ToLower() ?"active": "" )"><a href="@Url.Action("Index","TipoAgendamentoes")">Tipo agendam.</a></li>
    <li class="@( ViewContext.RouteData.Values["controller"].ToString().ToLower() == "AreaActuacaos".ToLower() ?"active": "" )"><a href="@Url.Action("Index","AreaActuacaos")">Serviços</a></li>
    <li class="@( ViewContext.RouteData.Values["controller"].ToString().ToLower() == "TipoDocumentoes".ToLower() ?"active": "" )"><a href="@Url.Action("Index","TipoDocumentoes")">Tipo documento</a></li>
    <li class="@( ViewContext.RouteData.Values["controller"].ToString().ToLower() == "Parentescoes".ToLower() ?"active": "" )"><a href="@Url.Action("Index","Parentescoes")">Parentesco</a></li>
    <li class="@( ViewContext.RouteData.Values["controller"].ToString().ToLower() == "Seguradoras".ToLower() ?"active": "" )"><a href="@Url.Action("Index","Seguradoras")">Seguradoras</a></li>
    <li class="@( ViewContext.RouteData.Values["controller"].ToString().ToLower() == "Provincias".ToLower() ?"active": "" )"><a href="@Url.Action("Index","Provincias")">Província</a></li>
    <li class="@( ViewContext.RouteData.Values["controller"].ToString().ToLower() == "Municipios".ToLower() ?"active": "" )"><a href="@Url.Action("Index","Municipios")">Município</a></li>
    <li class="@( ViewContext.RouteData.Values["controller"].ToString().ToLower() == "Funcionarios".ToLower() ?"active": "" )"><a href="@Url.Action("Index","Funcionarios")">Funcionário</a></li>
    <li class="@( ViewContext.RouteData.Values["controller"].ToString().ToLower() == "FuncionarioCategorias".ToLower() ?"active": "" )"><a href="@Url.Action("Index","FuncionarioCategorias")">Cat. Funcionário</a></li>
</ul>

vitamedline/MedLine/Views/Shared/_JsIncludes.cshtml
@if (ViewContext.RouteData.Values["action"].ToString().ToLower() == "Index".ToLower() ||
                                ViewContext.RouteData.Values["action"].ToString().ToLower() == "details".ToLower() ||
                                ViewContext.RouteData.Values["action"].ToString().ToLower() == "create".ToLower())
{
    <script src="~/Scripts/app/tabelas.js"></script>
}
@if (ViewContext.RouteData.Values["controller"].ToString().ToLower() == "Pacientes".ToLower())
{
    <script src="~/Scripts/app/paciente.js"></script>
}
@if (ViewContext.RouteData.Values["controller"].ToString().ToLower() == "Home".ToLower())
{
    <script src="~/Scripts/app/dashboard.js"></script>
}
else if (ViewContext.RouteData.Values["controller"].ToString().ToLower() == "Agendamentoes".ToLower())
{
    <script src="~/Scripts/app/agenda.js"></script>
}
else if (ViewContext.RouteData.Values["controller"].ToString().ToLower() == "Financas".ToLower())
{
    <script src="~/Scripts/app/financas.js"></script>
}
else if (ViewContext.RouteData.Values["controller"].ToString().ToLower() == "Definicoeos".ToLower())
{
    <script src="~/Scripts/app/main.js"></script>
}
else if (ViewContext.RouteData.Values["controller"].ToString().ToLower() == "Funcionarios".ToLower())
{
    <script src="~/Scripts/app/rh.js"></script>
}
else if (ViewContext.RouteData.Values["controller"].ToString().ToLower() == "Laboratorio".ToLower())
{
    <script src="~/Scripts/app/lab.js"></script>
}
else if (ViewContext.RouteData.Values["controller"].ToString().ToLower() == "Pagamento".ToLower())
{
    <script src="~/Scripts/app/payment.js"></script>
}
else if (ViewContext.RouteData.Values["controller"].ToString().ToLower() == "Consulta".ToLower())
{
    <script src="~/Scripts/app/timer.js"></script>
}

vitamedline/MedLine/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="">
<head>
    <meta charset="utf-8">
    <title>CareSys</title>
    <meta name="description" content="Sistema de gestão clínica">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="~/favicon.ico">
    <link rel="apple-touch-icon" href="~/apple-touch-icon.png">
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    @*<link rel="stylesheet" href="styles/vendor.css">
        <link rel="stylesheet" href="styles/main.css">*@

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <!--[if lt IE 10]>
    <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
        your browser</a> to improve your experience.</p>
    <![endif]-->
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top navbar-icons">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="index.html">
                        <div class="logo-container">
                            <div class="logo">
                                <img src="@Url.Content("~/Content/images/CareSys-logo.svg")" alt="" />
                            </div>
                        </div>
                    </a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="navbar-collapse">
                    @Html.Partial("_NavBar")
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container-fluid -->
        </nav>
    </header>
    <section>
        <div class="container">
            <div class="row">

                @RenderBody()

            </div>
        </div>
    </section>

    @*@Scripts.Render("~/bundles/jquery")*@
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @Scripts.Render("~/bundles/scripts")
    @RenderSection("scripts", required: false)
    @Html.Partial("_JsIncludes")

    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script>
        (function (b, o, i, l, e, r) {
            b.GoogleAnalyticsObject = l;
            b[l] || (b[l] =
                    function () {
                        (b[l].q = b[l].q || []).push(arguments)
                    });
            b[l].l = +new Date;
            e = o.createElement(i);
            r = o.getElementsByTagName(i)[0];
            e.src = 'https://www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e, r)
        }(window, document, 'script', 'ga'));
        ga('create', 'UA-XXXXX-X');
        ga('send', 'pageview');
    </script>
</body>
</html>

vitamedline/MedLine/Views/Shared/_NavBar.cshtml
<ul class="nav navbar-nav center">
    <li class="active">
        <a href="@Url.Action("Index", "Home")">
            <i class="pe-7s-graph"></i>

            <p>Painel</p>
        </a>
    </li>

    <li role="presentation" class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            <i class="pe-7s-shopbag"></i>
            <p>Consulta <span class="caret"></span></p>
        </a>
        <ul class="dropdown-menu">
            <li>
                <a href="@Url.Action("Index", "Agendamentoes")">
                    <i class="pe-7s-date pe-"></i>Agendamento
                </a>
            </li>
            <li>
                <a href="@Url.Action("Triagem", "Consulta")">
                    <i class="pe-7s-science"></i>Triagem
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Pagamento")">
                    <i class="pe-7s-cash"></i>Caixa
                </a>
            </li>
        </ul>
    </li>
    @*<li>
        <a href="@Url.Action("Index", "Agendamentoes")">
            <i class="pe-7s-date"></i>
            <p>Agenda</p>
        </a>
    </li>*@

    <li>
        <a href="@Url.Action("Index", "Pacientes")">
            <i class="pe-7s-users"></i>

            <p>Pacientes</p>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "Internamentos")">
            <i class="pe-7s-hourglass"></i>
            <p>Internamentos</p>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "Laboratorio")">
            <i class="pe-7s-magic-wand"></i>

            <p>Laboratório</p>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "Financas")">
            <i class="pe-7s-cash"></i>

            <p>Finanças</p>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "Consulta")">
            <i class="pe-7s-eyedropper"></i>
            <p>Médico</p>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "Relatório")">
            <i class="pe-7s-news-paper"></i>

            <p>Relatório</p>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "Definicoeos")">
            <i class="pe-7s-config"></i>

            <p>Definições</p>
        </a>
    </li>
</ul>
<div class="pull-right ferramentas-usuario">
    <div class="identificacao">
        <span class="nome">Benevides Lecontes</span>
        <span class="tipo">Biólogo</span>
    </div>
    <a class="btn dropdown-toggle" href="#" data-toggle="dropdown">
        <img src="@Url.Content("~/Content/images/Generic_Profile.jpg")">
    </a>

    <div class="dropdown-menu">
        <a href="#">
            <img src="@Url.Content("~/Content/images/Generic_Profile.jpg")" alt="">
        </a>

        <div class="detail">
            <a href="#">
                <h5>Benevides Lecontes</h5>
            </a><a href="#" class="edit">Editar conta</a>
        </div>
        <div class="clear logout">
            <a class="btn btn-xs btn-block" href="#">
                <i class="fa fa-power-off"></i> Sair
            </a>
        </div>
    </div>
</div>